# Generated by Django 2.1.4 on 2018-12-21 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BtechCSE', 'B.Tech-CSE'), ('BtechIT', 'B.Tech-IT'), ('BtechECE', 'B.Tech-ECE')], max_length=50)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth')], max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2018)])),
                ('image', models.ImageField(default='%course/%semester/%subject/%year.jpg', upload_to='media/papers/usict')),
            ],
        ),
    ]
